
DELETE http://localhost:3003/api/blogs/64ebe5eeecdf69e02d54f191



### 

POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Test",
  "author": "Nikita",
  "url": "someurl",
  "likes": "1"
}
###

GET http://localhost:3003/api/blogs
content-type: application/json

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Sixth blog by LEEEEE vkusniy",
  "author": "LEE",
  "url": "hhtt://vkusnuo/blabla/blublu",
  "likes": 666,
  "userId": "64f8eec381856900c4c92687"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Fifth blog by LEEEEE vkusniy",
  "author": "LEE",
  "url": "hhtt://vkusnuo/blabla/blublu",
  "userId": "64f8eec381856900c4c92687"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbnlhOTk5IiwiaWQiOiI2NGZiYTZhODBjM2U1ZDgzMzZiOWFjZTEiLCJpYXQiOjE2OTQyMjQ2MzcsImV4cCI6MTY5NDIyODIzN30.MOI_PeHdx2LsKCV_DFNGKUf0EQ5BfO4lTpYVLc-3ZDw

  {
  "title": "9199th blog by blabla vkusniy999",
  "author": "nikita",
  "url": "hhtt://vkusnuo/blabla/blublu999"
}

###
DELETE http://localhost:3003/api/blogs/64fba8700c3e5d8336b9ad08
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbnlhOTk5IiwiaWQiOiI2NGZiYTZhODBjM2U1ZDgzMzZiOWFjZTEiLCJpYXQiOjE2OTQyMjE2MzEsImV4cCI6MTY5NDIyNTIzMX0.-hCCsJDG5gzDwudBR2dQ6YnXLOFkcc9Tr1jiUMXZATI

###
POST http://localhost:3003/api/blogs
content-type: application/json

  {
  "title": "8th blog by LEEEEE vkusniy999",
  "author": "LEEe",
  "url": "hhtt://vkusnuo/blabla/blublu999"
}

###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "sonya999",
  "password": "dimitriv"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
"username": "sonya9999", 
"name": "Sonya", 
"password": "dimitriv"
}