
DELETE http://localhost:3003/api/blogs/64ebe5eeecdf69e02d54f191



### 

POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Test",
  "author": "Nikita",
  "url": "someurl",
  "likes": "1"
}
###

GET http://localhost:3003/api/blogs
content-type: application/json

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Sixth blog by LEEEEE vkusniy",
  "author": "LEE",
  "url": "hhtt://vkusnuo/blabla/blublu",
  "likes": 666,
  "userId": "64f8eec381856900c4c92687"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pa2l0YTk5OTkiLCJpZCI6IjY0ZmNlNDRhNzJiZDg5NWQ5MmI2NDkxZSIsImlhdCI6MTY5NDI5NTEzMSwiZXhwIjoxNjk0Mjk4NzMxfQ.9MjYsEnLiGfsjFCwY_GzsoNLn9vCdQCp0mm2JySLl-E
{
  "title": "Fifth blog by LEEEEE vkusniy",
  "author": "LEE",
  "url": "hhtt://vkusnuo/blabla/blublu",
}

###
POST http://localhost:3003/api/blogs/65427b92159e0fc70ea5655f/comments
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pa2l0YVdJTk5FUnByb2dyYW1tZXIiLCJpZCI6IjY1MzFhMjBlOWQ5YzJiNGRjNjc0YjI3NiIsImlhdCI6MTY5ODg1NTgwNywiZXhwIjoxNjk4ODU5NDA3fQ.OLKoie5yAKHnXUdtL-LFRw5cWdt2DCRFumER3ikrH84

  {
  "text": "testinggg"
}
###
POST http://localhost:3003/api/blogs
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pa2l0YVdJTk5FUnByb2dyYW1tZXIiLCJpZCI6IjY1MzFhMjBlOWQ5YzJiNGRjNjc0YjI3NiIsImlhdCI6MTY5ODg1NTgwNywiZXhwIjoxNjk4ODU5NDA3fQ.OLKoie5yAKHnXUdtL-LFRw5cWdt2DCRFumER3ikrH84

  {
  "title": "3d blog by blabla vkusniy999",
  "author": "nikita8888",
  "url": "hhtt://vkusnuo/blabla/blublu999"
}

###
DELETE http://localhost:3003/api/blogs/64fce52b72bd895d92b6493e
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbnlhODg4OCIsImlkIjoiNjRmY2U0ZTE3MmJkODk1ZDkyYjY0OTM0IiwiaWF0IjoxNjk0Mjk1Mjc2LCJleHAiOjE2OTQyOTg4NzZ9.1mHqi_mXpH7n5FMk10NPM4zsLP8M2u35TMK8T4iQDpU

###
POST http://localhost:3003/api/blogs
content-type: application/json

  {
  "title": "8th blog by LEEEEE vkusniy999",
  "author": "LEEe",
  "url": "hhtt://vkusnuo/blabla/blublu999"
}

###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "nikitaWINNERprogrammer",
  "password": "dimi"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
"username": "nikitaWINNERprogrammer", 
"name": "nikita", 
"password": "dimi"
}