
DELETE http://localhost:3003/api/blogs/64ebe5eeecdf69e02d54f191



### 

POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Test",
  "author": "Nikita",
  "url": "someurl",
  "likes": "1"
}
###

GET http://localhost:3003/api/blogs
content-type: application/json

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Sixth blog by LEEEEE vkusniy",
  "author": "LEE",
  "url": "hhtt://vkusnuo/blabla/blublu",
  "likes": 666,
  "userId": "64f8eec381856900c4c92687"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Fifth blog by LEEEEE vkusniy",
  "author": "LEE",
  "url": "hhtt://vkusnuo/blabla/blublu",
  "userId": "64f8eec381856900c4c92687"
}